# Site settings
title: De Nicolás Romero
email: your-email@example.com
description: >- 
  denicolasromero.com es un sitio web
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: denicolasromero
google_analytics: UA-130293099-3


minima:
  date_format: "%-d de %B del %Y"
  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss


# Build settings
plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
